services:
  - type: web
    name: dash-lfs
    env: static
    rootDir: dashboard-app
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
